name: diccionario_culinario
description: Diccionario culinario multilenguaje (ES/EN/DE/FR) con modo offline, favoritos, historial y pronunciaciÃ³n.
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  flutter_tts: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/diccionario.csv
